[build]
  publish = "frontend"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/about.html"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/contact.html"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/portfolio"
  to = "/pages/portfolio.html"
  status = 200

[[redirects]]
  from = "/portfolio.html"
  to = "/pages/portfolio.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/pages/blog.html"
  status = 200

[[redirects]]
  from = "/blog.html"
  to = "/pages/blog.html"
  status = 200
  
[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/19390/elitedevs.work"
  status = 301
  force = true
